@startuml
left to right direction

class Usuario {
  +Nombre : String
  +Monedero : int
  +Buscar_precios_de_comida()
}

Class Ubicación {
    +Numero_de_tiendas: String
    +Informar_disponibilidad()
}

class Fuera_de_universidad{
     +Horario : int

}

Class Universidad{
     +Elegir_lugar()
}


class du_Nord {
   +nombre : String
   +lista : String
   +Disponiblidad()
   +mostrar_productos()
}

Class DunordExpress{
     +Horario : int
}

Class DunordTerraza{
     +Horario : int

}
class Menu {
   
   +precio: int
   +cantida: int
   +seleccionar_precio()
   +seleccionar_cantidad()
}

class Comida {
   +nombre : String
   +ingredientes : String

}

Class Producto_final{
   +Total : int
   +Mostrar total()
}

Usuario --* Ubicación
Ubicación <|-- Universidad
Ubicación <|-- Fuera_de_universidad
Universidad --* du_Nord
du_Nord <|-- DunordExpress
du_Nord <|-- DunordTerraza
Menu <|-- DunordExpress
Menu <|-- DunordTerraza
Menu --* Comida
Comida --* Producto_final


@enduml
